name            = "west-casa-router"
main            = "index.js"
compatibility_date = "2024-01-01"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

routes = [
  { pattern = "west-casa.com/*", zone_name = "west-casa.com" }
]
